### ISSUE TITLE
box_scores function doesn't work!!!

### ISSUE THREAD

**Issue by TheRabbot17** [abresler/nbastatR#21]
Im using this function in my R Project with this parameters:
boxdata_scores <- box_scores(game_ids = c(0011800001), box_score_types = c("Traditional"), result_types = c("team"), join_data = TRUE, assign_to_environment = TRUE, return_message = TRUE)

And return me an error:
Unknown or uninitialised column: 'typeResult'.

Can you solve this problem?

**Comment by TheRabbot17** [comment]
I use this id AND the same without the first 2 00 (11800001). The response is the same

**Comment by abresler** [comment]
This works for me, try reinstalling the package and see if it works.  If you use a VPN or a firewall that may be the issue otherwise I am not sure what to tell you.

Good luck
<img width="557" alt="Screen Shot 2019-03-14 at 9 04 15 AM" src="https://user-images.githubusercontent.com/740564/54359093-46b6aa80-4638-11e9-957e-2bd370aa0598.png">
